local Flux = loadstring(game:HttpGet"https://pastebin.com/raw/KVQi1dRm")()

local win = Flux:Window("Moonless Hub", "Game Name | MlH v0.1", Color3.fromRGB(212, 57, 165), Enum.KeyCode.RightControl)
local tab = win:Tab("Change Logs", "http://www.roblox.com/asset/?id=54479722")
--[[
tab:Button("Kill all", "This function may not work sometimes and you can get banned.", function()
Flux:Notification("Killed all players successfully!", "Alright")
end)
tab:Label("This is just a label.", "Description ?")
tab:Line()
tab:Toggle("Auto-Farm Coins", "Automatically collects coins for you!", function(t)
print(t)
end)
tab:Slider("Walkspeed", "Makes your faster.", 0, 100,16,function(t)
print(t)
end)
tab:Dropdown("Part to aim at", {"Torso","Head","Penis"}, function(t)
print(t)
end)
tab:Colorpicker("ESP Color", Color3.fromRGB(255,1,1), function(t)
print(t)
end)
tab:Textbox("Gun Power", "This textbox changes your gun power, so you can kill everyone faster and easier.", true, function(t)
print(t)
end)
tab:Bind("Kill Bind", Enum.KeyCode.Q, function()
print("Killed a random person!")
end)]]--
win:Tab("Scripts", "http://www.roblox.com/asset/?id=6031075938")
win:Tab("Player", "http://www.roblox.com/asset/?id=8099668652")
win:Tab("About Us", "http://www.roblox.com/asset/?id=8164258905")